<?php

use App\Http\Middleware\Api\V1\Ecommerce\IsShopMiddleware;
use App\Http\Middleware\Api\V1\Ecommerce\JwtMiddleware;

$base       = basename(__FILE__, '.php');
$base_shop  = 'shop';
return  [

    'prefix'        => $base,
    'label'         => 'Travel',
    'middleware'    => [],
    'routes'        => [
        // category
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\CategoryController::class,
            'uri'           => 'category',
            'name'          => $base . 'category.index',
            'methods'       => ['get'],
            'action'        => 'index',
        ],
        // banner
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\BannerController::class,
            'uri'           => 'banner',
            'name'          => $base . 'banner.index',
            'methods'       => ['get'],
            'action'        => 'index',
        ],
        // voucher_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\VoucherController::class,
            'uri'           => 'voucher',
            'name'          => $base . 'voucher.index',
            'methods'       => ['get'],
            'action'        => 'index',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\VoucherController::class,
            'uri'           => 'voucher/my_voucher',
            'name'          => $base . 'voucher.my_voucher',
            'methods'       => ['get'],
            'action'        => 'my_voucher',
        ],
        // product
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\ProductController::class,
            'uri'           => 'product',
            'name'          => $base . 'product.index',
            'methods'       => ['get'],
            'action'        => 'index',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\ProductController::class,
            'uri'           => 'product/filter',
            'name'          => $base . 'product.filter',
            'methods'       => ['get'],
            'action'        => 'filter',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\ProductController::class,
            'uri'           => 'product/search',
            'name'          => $base . 'product.search',
            'methods'       => ['get'],
            'action'        => 'search',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\ProductController::class,
            'uri'           => 'product/{slug}',
            'name'          => $base . 'product.show',
            'methods'       => ['get'],
            'action'        => 'show',
        ],
        // contact_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\ProductController::class,
            'uri'           => 'contact',
            'name'          => $base . 'contact.create',
            'methods'       => ['post'],
            'action'        => 'contact',
        ],

        // post
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PostController::class,
            'uri'           => 'post',
            'name'          => $base . 'post.index',
            'methods'       => ['get'],
            'action'        => 'index',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PostController::class,
            'uri'           => 'post/{post_type}/list',
            'name'          => $base . 'post.list',
            'methods'       => ['get'],
            'action'        => 'index',
        ],
        // live
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\LivestreamController::class,
            'uri'           => 'livestream',
            'name'          => $base . 'livestream.index',
            'methods'       => ['get'],
            'action'        => 'index',
        ],
        // shop
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\ShopController::class,
            'uri'           => 'shop',
            'name'          => $base . 'shop.index',
            'methods'       => ['get'],
            'action'        => 'index',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\ShopController::class,
            'uri'           => 'shop/{slug}/show',
            'name'          => $base . 'shop.show',
            'methods'       => ['get'],
            'action'        => 'show',
        ],
        // auth
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AuthController::class,
            'uri'           => 'auth/register',
            'name'          => $base . 'auth.register',
            'methods'       => ['post'],
            'action'        => 'register',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AuthController::class,
            'uri'           => 'auth/check-email',
            'name'          => $base . 'auth.check-email',
            'methods'       => ['post'],
            'action'        => 'checkEmail',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AuthController::class,
            'uri'           => 'auth/verify-email',
            'name'          => $base . 'auth.verify-email',
            'methods'       => ['post'],
            'action'        => 'verifyEmail',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AuthController::class,
            'uri'           => 'auth/register',
            'name'          => $base . 'auth.register',
            'methods'       => ['post'],
            'action'        => 'register',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AuthController::class,
            'uri'           => 'auth/login',
            'name'          => $base . 'auth.login',
            'methods'       => ['post'],
            'action'        => 'login',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AuthController::class,
            'uri'           => 'auth/withgoogle',
            'name'          => $base . 'auth.withgoogle',
            'methods'       => ['post'],
            'action'        => 'withgoogle',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AuthController::class,
            'uri'           => 'auth/forgotpassword',
            'name'          => $base . 'auth.forgotpassword',
            'methods'       => ['post'],
            'action'        => 'forgotpassword',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AuthController::class,
            'uri'           => 'auth/changenewpassword',
            'name'          => $base . 'auth.changenewpassword',
            'methods'       => ['post'],
            'action'        => 'changenewpassword',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AuthController::class,
            'uri'           => 'auth/refresh-token',
            'name'          => $base . 'auth.refresh-token',
            'methods'       => ['post'],
            'action'        => 'refreshToken',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AuthController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'me',
            'name'          => $base . 'auth.me',
            'methods'       => ['get'],
            'action'        => 'me',
        ],
        // user_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\UserController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'user/coin/history',
            'name'          => $base . 'user.coin.history',
            'methods'       => ['get'],
            'action'        => 'coin_history',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\UserController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'user/update-info',
            'name'          => $base . 'user.update-info',
            'methods'       => ['post'],
            'action'        => 'update_info',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\UserController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'user/change_password',
            'name'          => $base . 'user.change_password',
            'methods'       => ['post'],
            'action'        => 'change_password',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\UserController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'user/voucher',
            'name'          => $base . 'user.voucher',
            'methods'       => ['get'],
            'action'        => 'my_voucher',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\UserController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'user/voucher/save',
            'name'          => $base . 'user.voucher.save',
            'methods'       => ['post'],
            'action'        => 'save_voucher',
        ],

        // cart
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\CartController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'cart/asyn_cart',
            'name'          => $base . 'cart.asyn_cart',
            'methods'       => ['post'],
            'action'        => 'asyn_cart',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\CartController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'cart/add_to_cart',
            'name'          => $base . 'cart.add_to_cart',
            'methods'       => ['post'],
            'action'        => 'add_to_cart',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\CartController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'cart/update_cart',
            'name'          => $base . 'cart.update_cart',
            'methods'       => ['post'],
            'action'        => 'update_cart',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\OrderController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'order/checkout',
            'name'          => $base . 'order.checkout',
            'methods'       => ['post'],
            'action'        => 'checkout',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\CartController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'cart/get_fee_ship',
            'name'          => $base . 'cart.get_fee_ship',
            'methods'       => ['get'],
            'action'        => 'get_fee_ship',
        ],
        // notify_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\NotifyController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'notify',
            'name'          => $base . 'notify.index',
            'methods'       => ['get'],
            'action'        => 'index',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\NotifyController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'notify/{id}',
            'name'          => $base . 'notify.show',
            'methods'       => ['get'],
            'action'        => 'show',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\NotifyController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'notify/read-all',
            'name'          => $base . 'notify.readall',
            'methods'       => ['post'],
            'action'        => 'readAll',
        ],
        // address
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AddressController::class,
            'middleware'    => [],
            'uri'           => 'address/provinces',
            'name'          => $base . 'address.provinces',
            'methods'       => ['get'],
            'action'        => 'get_provinces',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AddressController::class,
            'middleware'    => [],
            'uri'           => 'address/districts/{province_id}',
            'name'          => $base . 'address.district',
            'methods'       => ['get'],
            'action'        => 'get_district',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AddressController::class,
            'middleware'    => [],
            'uri'           => 'address/wards/{district_id}',
            'name'          => $base . 'address.wards',
            'methods'       => ['get'],
            'action'        => 'get_ward',
        ],
        // user_adress_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AddressController::class,
            'middleware'    => [],
            'uri'           => 'user/address',
            'name'          => $base . 'user.address.get_address',
            'methods'       => ['get'],
            'action'        => 'get_address',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AddressController::class,
            'middleware'    => [],
            'uri'           => 'user/address',
            'name'          => $base . 'user.address.create_address',
            'methods'       => ['post'],
            'action'        => 'create_address',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AddressController::class,
            'middleware'    => [],
            'uri'           => 'user/address/address-default',
            'name'          => $base . 'user.address.get_default_address',
            'methods'       => ['get'],
            'action'        => 'get_default_address',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AddressController::class,
            'middleware'    => [],
            'uri'           => 'user/address/{address_id}',
            'name'          => $base . 'user.address.get_address_by_id',
            'methods'       => ['get'],
            'action'        => 'get_address_by_id',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AddressController::class,
            'middleware'    => [],
            'uri'           => 'user/address/{address_id}',
            'name'          => $base . 'user.address.update_address',
            'methods'       => ['patch'],
            'action'        => 'update_address',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AddressController::class,
            'middleware'    => [],
            'uri'           => 'user/address/{address_id}',
            'name'          => $base . 'user.address.delete_address',
            'methods'       => ['delete'],
            'action'        => 'delete_address',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\AddressController::class,
            'middleware'    => [],
            'uri'           => 'user/address/set-default/{address_id}',
            'name'          => $base . 'user.address.set_default_address',
            'methods'       => ['patch'],
            'action'        => 'set_default_address',
        ],

        // payment_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PaymentController::class,
            'middleware'    => [],
            'uri'           => 'payment/banks',
            'name'          => $base . 'payment.banks',
            'methods'       => ['get'],
            'action'        => 'get_banks',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PaymentController::class,
            'middleware'    => [],
            'uri'           => 'payment/get_settings',
            'name'          => $base . 'payment.get_settings',
            'methods'       => ['get'],
            'action'        => 'get_settings',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PaymentController::class,
            'middleware'    => [],
            'uri'           => 'payment/payment_methods',
            'name'          => $base . 'payment.payment_methods',
            'methods'       => ['get'],
            'action'        => 'get_payment_methods',
        ],
        // file
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\FileUploadController::class,
            'middleware'    => [],
            'uri'           => 'file/payment_methods',
            'name'          => $base . 'file.upload',
            'methods'       => ['post'],
            'action'        => 'upload_file',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\FileUploadController::class,
            'middleware'    => [],
            'uri'           => 'file/uploads',
            'name'          => $base . 'file.uploads',
            'methods'       => ['post'],
            'action'        => 'upload_files',
        ],
        //  user_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\UserController::class,
            'middleware'    => [],
            'uri'           => 'user/payment_methods',
            'name'          => $base . 'file.upload',
            'methods'       => ['post'],
            'action'        => 'upload_file',
        ],
        // order_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\OrderController::class,
            'middleware'    => [],
            'uri'           => 'order/order_payment_information',
            'name'          => $base . 'order.order_payment_information',
            'methods'       => ['post'],
            'action'        => 'order_payment_information',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\OrderController::class,
            'middleware'    => [],
            'uri'           => 'order/check_status_payment',
            'name'          => $base . 'order.check_status_payment',
            'methods'       => ['post'],
            'action'        => 'check_status_payment',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\OrderController::class,
            'middleware'    => [],
            'uri'           => 'order/vnpay_info_payment',
            'name'          => $base . 'order.vnpay_info_payment',
            'methods'       => ['post'],
            'action'        => 'checkoutVnpay',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\OrderController::class,
            'middleware'    => [],
            'uri'           => 'order/momo_info_payment',
            'name'          => $base . 'order.momo_info_payment',
            'methods'       => ['post'],
            'action'        => 'momo_info_payment',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\OrderController::class,
            'middleware'    => [],
            'uri'           => 'order/verify_payment',
            'name'          => $base . 'order.verify_payment',
            'methods'       => ['post'],
            'action'        => 'verify_payment',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\OrderController::class,
            'middleware'    => [],
            'uri'           => 'order/history',
            'name'          => $base . 'order.history',
            'methods'       => ['get'],
            'action'        => 'my_order_history',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\OrderController::class,
            'middleware'    => [],
            'uri'           => 'order/history/{id}',
            'name'          => $base . 'order.history.my_order_history_detail',
            'methods'       => ['get'],
            'action'        => 'my_order_history_detail',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\OrderController::class,
            'middleware'    => [],
            'uri'           => 'order/history/{id}/cancel',
            'name'          => $base . 'order.history.cancel',
            'methods'       => ['patch'],
            'action'        => 'cancel_order',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\OrderController::class,
            'middleware'    => [],
            'uri'           => 'order/checkout',
            'name'          => $base . 'order.checkout',
            'methods'       => ['post'],
            'action'        => 'checkout',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\OrderController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'order/checkout',
            'name'          => $base . 'order.checkout',
            'methods'       => ['post'],
            'action'        => 'checkout',
        ],
        // post_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PostController::class,
            'middleware'    => [],
            'uri'           => 'post/detail/{slug}',
            'name'          => $base . 'post.detail',
            'methods'       => ['get'],
            'action'        => 'getPostBySlug',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PostController::class,
            'middleware'    => [],
            'uri'           => 'post/category_post',
            'name'          => $base . 'post.getPostCategory',
            'methods'       => ['get'],
            'action'        => 'getPostCategory',
        ],
        // ===
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PostController::class,
            'middleware'    => [],
            'uri'           => 'post/create_post',
            'name'          => $base . 'post.create_post',
            'methods'       => ['post'],
            'action'        => 'createPost',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PostController::class,
            'middleware'    => [],
            'uri'           => 'post/edit_post/{id}',
            'name'          => $base . 'post.edit_post',
            'methods'       => ['post'],
            'action'        => 'editPostById',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PostController::class,
            'middleware'    => [],
            'uri'           => 'post/my_post',
            'name'          => $base . 'post.my_post',
            'methods'       => ['get'],
            'action'        => 'my_post',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PostController::class,
            'middleware'    => [],
            'uri'           => 'post/post_slug_shop/{id}',
            'name'          => $base . 'post.getPostByIDPostShop',
            'methods'       => ['get'],
            'action'        => 'getPostByIDPostShop',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PostController::class,
            'middleware'    => [],
            'uri'           => 'post/create_post',
            'name'          => $base . 'post.create_post',
            'methods'       => ['post'],
            'action'        => 'createPost',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PostController::class,
            'middleware'    => [],
            'uri'           => 'post/create_post',
            'name'          => $base . 'post.create_post',
            'methods'       => ['post'],
            'action'        => 'createPost',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PostController::class,
            'middleware'    => [],
            'uri'           => 'post/create_post',
            'name'          => $base . 'post.create_post',
            'methods'       => ['post'],
            'action'        => 'createPost',
        ],

        // ====
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PostController::class,
            'middleware'    => [],
            'uri'           => 'post/sidebar/{post_type}',
            'name'          => $base . 'post.post_sidebar',
            'methods'       => ['get'],
            'action'        => 'post_sidebar',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PostController::class,
            'middleware'    => [],
            'uri'           => 'post/{post_type}/list',
            'name'          => $base . 'post.index',
            'methods'       => ['get'],
            'action'        => 'index',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\PostController::class,
            'middleware'    => [],
            'uri'           => 'post/{type}',
            'name'          => $base . 'post.getPostFilter',
            'methods'       => ['get'],
            'action'        => 'getPostFilter',
        ],
        // chat_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\ChatController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'chat/list',
            'name'          => $base . 'chat.list',
            'methods'       => ['get'],
            'action'        => 'list',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\ChatController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'chat/by_id/{cons_id}',
            'name'          => $base . 'chat.by_id',
            'methods'       => ['get'],
            'action'        => 'by_id',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\ChatController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'chat/message/{id}',
            'name'          => $base . 'chat.getMessage',
            'methods'       => ['get'],
            'action'        => 'getMessage',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\ChatController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'chat/send_message',
            'name'          => $base . 'chat.sendMessage',
            'methods'       => ['post'],
            'action'        => 'sendMessage',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\ChatController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'chat/get_conversations',
            'name'          => $base . 'chat.getConversations',
            'methods'       => ['get'],
            'action'        => 'getConversations',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\ChatController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'chat/message-not-read',
            'name'          => $base . 'chat.countMessageNotRead',
            'methods'       => ['get'],
            'action'        => 'countMessageNotRead',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\ChatController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => 'chat/{id}',
            'name'          => $base . 'chat.deleteMessage',
            'methods'       => ['delete'],
            'action'        => 'deleteMessage',
        ],
        // ...shop_route
        // ...$shop
        // ========================================== shop start=====================================
        // banner_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\BannerController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/banner',
            'name'          => $base_shop . '.banner.index',
            'methods'       => ['get'],
            'action'        => 'banner_index',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\BannerController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/banner/{id}',
            'name'          => $base_shop . '.banner.banner_get',
            'methods'       => ['get'],
            'action'        => 'banner_get',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\BannerController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/banner',
            'name'          => $base_shop . '.banner.banner_create',
            'methods'       => ['post'],
            'action'        => 'banner_create',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\BannerController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/banner/{id}',
            'name'          => $base_shop . '.banner.banner_update',
            'methods'       => ['post'],
            'action'        => 'banner_update',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\BannerController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/banner/{id}',
            'name'          => $base_shop . '.banner.banner_delete',
            'methods'       => ['delete'],
            'action'        => 'banner_delete',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\BannerController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/banner/{id}',
            'name'          => $base_shop . '.banner.banner_restore',
            'methods'       => ['patch'],
            'action'        => 'banner_restore',
        ],
        // livestream_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\LiveStreamController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/live',
            'name'          => $base_shop . '.live.create',
            'methods'       => ['post'],
            'action'        => 'create',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\LiveStreamController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/live',
            'name'          => $base_shop . '.live.index',
            'methods'       => ['get'],
            'action'        => 'index',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\LiveStreamController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/live/current',
            'name'          => $base_shop . '.live.current',
            'methods'       => ['get'],
            'action'        => 'current',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductLiveController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/live/add-product',
            'name'          => $base_shop . '.live.add-product',
            'methods'       => ['post'],
            'action'        => 'addProduct',
        ],

        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\LiveStreamController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => $base_shop . '/live/chat',
            'name'          => $base_shop . '.live.chat',
            'methods'       => ['post'],
            'action'        => 'sendChat',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\LiveStreamController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => $base_shop . '/live/detail/{name}',
            'name'          => $base_shop . '.live.detail',
            'methods'       => ['get'],
            'action'        => 'detail',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\LiveStreamController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => $base_shop . '/live/history/{name}',
            'name'          => $base_shop . '.live.history',
            'methods'       => ['get'],
            'action'        => 'history',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductLiveController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => $base_shop . '/live/current-product',
            'name'          => $base_shop . '.live.current-product',
            'methods'       => ['get'],
            'action'        => 'currentProduct',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\LiveStreamController::class,
            'middleware'    => [],
            'uri'           => $base_shop . '/live/verify',
            'name'          => $base_shop . '.live.verify',
            'methods'       => ['post'],
            'action'        => 'verify',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductLiveController::class,
            'middleware'    => [JwtMiddleware::class],
            'uri'           => $base_shop . '/user/add-cart',
            'name'          => $base_shop . '.live.current-product',
            'methods'       => ['get'],
            'action'        => 'addCart',
        ],
        // order_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\OrderController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/order',
            'name'          => $base_shop . '.order.order_index',
            'methods'       => ['get'],
            'action'        => 'order_index',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\OrderController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/order/{id}',
            'name'          => $base_shop . '.order.order_get',
            'methods'       => ['get'],
            'action'        => 'order_get',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\OrderController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/order',
            'name'          => $base_shop . '.order.order_update_status',
            'methods'       => ['put'],
            'action'        => 'order_update_status',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\OrderController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/order/{id}/detail',
            'name'          => $base_shop . '.order.order_detail_index',
            'methods'       => ['get'],
            'action'        => 'order_detail_index',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\OrderController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/order/{id}/detail/{id_detail}',
            'name'          => $base_shop . '.order.order_detail_get',
            'methods'       => ['get'],
            'action'        => 'order_detail_get',
        ],
        // product_review_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductReviewController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/review',
            'name'          => $base_shop . '.review.review_index',
            'methods'       => ['get'],
            'action'        => 'review_index',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductReviewController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/review/{product_id}',
            'name'          => $base_shop . '.review.review_get',
            'methods'       => ['get'],
            'action'        => 'review_get',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductReviewController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/review/{product_id}/detail/{id}',
            'name'          => $base_shop . '.review.review_detail_get',
            'methods'       => ['get'],
            'action'        => 'review_detail_get',
        ],
        // product_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductImportController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/import',
            'name'          => $base_shop . '.product.import',
            'methods'       => ['post'],
            'action'        => 'import',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product',
            'name'          => $base_shop . '.product.product_index',
            'methods'       => ['get'],
            'action'        => 'product_index',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/{id}',
            'name'          => $base_shop . '.product.product_get',
            'methods'       => ['get'],
            'action'        => 'product_get',
        ],

        // 1
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product',
            'name'          => $base_shop . '.product.product_create',
            'methods'       => ['post'],
            'action'        => 'product_create',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/{id}',
            'name'          => $base_shop . '.product.product_update',
            'methods'       => ['post'],
            'action'        => 'product_update',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/{id}/info',
            'name'          => $base_shop . '.product.product_update_info',
            'methods'       => ['post'],
            'action'        => 'product_update_info',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/{id}/cate',
            'name'          => $base_shop . '.product.product_update_cate',
            'methods'       => ['get'],
            'action'        => 'product_update_cate',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/{id}/warehouse',
            'name'          => $base_shop . '.product.product_update_warehouse',
            'methods'       => ['post'],
            'action'        => 'product_update_warehouse',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/{id}/stock',
            'name'          => $base_shop . '.product.product_update_stock',
            'methods'       => ['post'],
            'action'        => 'product_update_stock',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/{id}/shipping',
            'name'          => $base_shop . '.product.product_update_shipping',
            'methods'       => ['post'],
            'action'        => 'product_update_shipping',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/{id}/media',
            'name'          => $base_shop . '.product.product_update_media',
            'methods'       => ['post'],
            'action'        => 'product_update_media',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/{id}/clone',
            'name'          => $base_shop . '.product.product_clone',
            'methods'       => ['post'],
            'action'        => 'product_clone',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/{id}/attribute/{attribute_id}',
            'name'          => $base_shop . '.product.product_update_attribute_by_id',
            'methods'       => ['post'],
            'action'        => 'product_update_attribute_by_id',
        ],
        // 2
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/{id}',
            'name'          => $base_shop . '.product.product_restore',
            'methods'       => ['patch'],
            'action'        => 'product_restore',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/{id}',
            'name'          => $base_shop . '.product.product_delete',
            'methods'       => ['delete'],
            'action'        => 'product_delete',
        ],

        // 3
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/{id}/visibility',
            'name'          => $base_shop . '.product.product_update_visibility',
            'methods'       => ['get'],
            'action'        => 'product_update_visibility',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/{id}/attribute/{attribute_id}',
            'name'          => $base_shop . '.product.product_delete_attribute_by_id',
            'methods'       => ['delete'],
            'action'        => 'product_delete_attribute_by_id',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ProductController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/product/image/{image_id}',
            'name'          => $base_shop . '.product.product_delete_image_by_id',
            'methods'       => ['delete'],
            'action'        => 'product_delete_image_by_id',
        ],
        // setting_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ShopController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/setting',
            'name'          => $base_shop . '.setting.shop_update_info',
            'methods'       => ['post'],
            'action'        => 'shop_update_info',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ShopController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/setting/bank/{id}',
            'name'          => $base_shop . '.setting.shop_delete_bank_account',
            'methods'       => ['delete'],
            'action'        => 'shop_delete_bank_account',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ShopController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/setting/verify-email-shop',
            'name'          => $base_shop . '.setting.verify-email-shop',
            'methods'       => ['post'],
            'action'        => 'verify_email_shop',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\ShopController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/setting/shop_info',
            'name'          => $base_shop . '.setting.shop_info',
            'methods'       => ['get'],
            'action'        => 'shop_info',
        ],
        // voucher_route
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\VoucherController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/voucher',
            'name'          => $base_shop . '.voucher.voucher_index',
            'methods'       => ['get'],
            'action'        => 'voucher_index',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\VoucherController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/voucher/{id}',
            'name'          => $base_shop . '.voucher.voucher_get',
            'methods'       => ['get'],
            'action'        => 'voucher_get',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\VoucherController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/voucher',
            'name'          => $base_shop . '.voucher.voucher_create',
            'methods'       => ['post'],
            'action'        => 'voucher_create',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\VoucherController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/voucher/{id}',
            'name'          => $base_shop . '.voucher.voucher_clone',
            'methods'       => ['put'],
            'action'        => 'voucher_clone',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\VoucherController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/voucher/{id}',
            'name'          => $base_shop . '.voucher.voucher_update',
            'methods'       => ['post'],
            'action'        => 'voucher_update',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\VoucherController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/voucher/{id}',
            'name'          => $base_shop . '.voucher.voucher_delete',
            'methods'       => ['delete'],
            'action'        => 'voucher_delete',
        ],
        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\VoucherController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/voucher/{id}',
            'name'          => $base_shop . '.voucher.voucher_restore',
            'methods'       => ['patch'],
            'action'        => 'voucher_restore',
        ],

        [
            'controller'    =>   \App\Http\Controllers\Api\V1\Ecommerce\Shop\DashboardController::class,
            'middleware'    => [JwtMiddleware::class, IsShopMiddleware::class],
            'uri'           => $base_shop . '/dashboard',
            'name'          => $base_shop . '.dashboard.dashboard',
            'methods'       => ['get'],
            'action'        => 'dashboard',
        ],

    ]

];
