version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8005:8005
    networks:
      - laravel
    command: php artisan serve --host 0.0.0.0 --port 8005
networks:
  laravel:
    driver: bridge
# volumes:
#   dbdata:
#     driver: local
volumes:
  es_data:
    driver: local