<?php
return [
    'TABLE_CATEGORY'                => 'ecommerce_categories',
    'TABLE_SHOP'                    => 'ecommerce_shops',
    'TABLE_SETTING'                 => 'ecommerce_settings',
    'TABLE_PAYMENT_METHOD'          => 'ecommerce_payment_methods',
    'TABLE_ATTRIBUTE_NAME'          => 'ecommerce_attribute_names',
    'TABLE_BRAND'                   => 'ecommerce_brands',
    'TABLE_INVENTORY_LOG'           => 'ecommerce_inventory_logs',
    'TABLE_PRICE_HISTORY'           => 'ecommerce_price_historys',
    'TABLE_PRICE_LOG'               => 'ecommerce_price_logs',
    'TABLE_PRODUCT'                 => 'ecommerce_products',
    'TABLE_PRODUCT_ATTRIBUTE'       => 'ecommerce_product_attributes',
    'TABLE_PRODUCT_IMAGE'           => 'ecommerce_product_images',
    'TABLE_PRODUCT_LIKE_REVIEW'     => 'ecommerce_product_like_reviews',
    'TABLE_PRODUCT_LIKE'            => 'ecommerce_product_likes',
    'TABLE_PRODUCT_LOVE'            => 'ecommerce_product_loves',
    'TABLE_PRODUCT_REVIEW'          => 'ecommerce_product_reviews',
    'TABLE_PRODUCT_REVIEW_METRIC'   => 'ecommerce_product_review_metrics',
    'TABLE_PRODUCT_REVIEW_REPLY'    => 'ecommerce_product_review_replies',
    'TABLE_PRODUCT_SHIPPING'        => 'ecommerce_product_shippings',
    'TABLE_BANNER'                  => 'ecommerce_banners',
    'TABLE_VOUCHER'                 => 'ecommerce_vouchers',
    'TABLE_USER_VOUCHER'            => 'ecommerce_user_vouchers',
    'TABLE_CATEGORY_POST'           => 'ecommerce_categories_posts',
    'TABLE_POST_TYPE'               => 'ecommerce_post_types',
    'TABLE_POST'                    => 'ecommerce_posts',
    'TABLE_TAG'                     => 'ecommerce_tags',
    'TABLE_POST_TAG_RELATION'       => 'ecommerce_post_tag_relations',
    'TABLE_ORDER'                   => 'ecommerce_orders',
    'TABLE_ORDER_SHOP'              => 'ecommerce_order_shops',
    'TABLE_ORDER_DETAIL'            => 'ecommerce_order_details',
    'TABLE_LIVESTREAM'              => 'ecommerce_livestreams',
    'TABLE_LIVE_CHAT'               => 'ecommerce_live_chats',
    'TABLE_PRODUCT_LIVE'            => 'ecommerce_product_lives',
    'TABLE_COIN_RULE'               => 'ecommerce_coin_rules',
    'TABLE_COIN_TRANSACTION'        => 'ecommerce_coin_transactions',
    'TABLE_BANK'                    => 'ecommerce_banks',
    'TABLE_USER_BANK'               => 'ecommerce_user_banks',
    'TABLE_SHOP_FOLLOW'             => 'ecommerce_shop_follows',


];
