<?php
return [
    'TABLE_ORANIZATION'         => 'organizations',
    'TABLE_USER'                => 'users',
    'TABLE_ROLE'                => 'roles',
    'TABLE_PERMISSION'          => 'permissions',
    'TABLE_USER_ROLE'           => 'user_roles',
    'TABLE_ROLE_PERMISSION'     => 'role_permissions',
    'TABLE_USER_PERMISSION'     => 'user_permissions',
    'TABLE_DOCUMENT'            => 'documents',
    'TABLE_RESOURCE_PERMISSION' => 'resource_permissions',
    'TABLE_FILE_UPLOAD'         => 'file_uploads',
    'TABLE_PASSWORD_RESET_TOKEN' => 'password_reset_tokens',
    'TABLE_PROVINCE'            => 'general_provinces',
    'TABLE_DISTRICT'            => 'districts',
    // 'TABLE_WARD'                => 'wards',
    // 'TABLE_WARD'                => 'wards',
    'TABLE_WARD'                => 'general_wards',
    'TABLE_COUNTRY'                => 'general_country',
];
